---
title: 'Dashboard: My first prototipe'
format: dashboard
---

```{r}
library(devtools)
load_all('~/git/amphidata/')

amphi_load_packages(
  update_packages = FALSE)

df_g <- load_dimensions_golvin(
    filtrar_provincia = NULL,
    filtrar_pais = NULL,
    seleccionar_columnes = NULL,
    format_llarg = FALSE,
    etiquetes = TRUE)
    
```

```{r}
#| label: distrb-by-prov-country
#| title: Distribució per província romana i país actual
#| fig-asp: 0.3
#| fig-width: 10
(
  df_g %>%
    count(
      etiq_pais_i, etiq_provincia_i,
      name = 'n_amphi') %>%
    dplyr::mutate(
      etiq_pais_i = forcats::fct_reorder(
        etiq_pais_i, n_amphi,
        .fun = max,
        .desc = FALSE),
      n_amphi_cat = cut(
        n_amphi,
        breaks = c(0, 1, 4, 10, Inf),
        labels = c('1', '2-4', '5-10', '+10'),
        right = TRUE,
        include.lowest = TRUE)
      ) %>%
  ggplot(
      aes(
        x = etiq_provincia_i,
        y = etiq_pais_i)) +
  geom_point(
      aes(
        size = n_amphi_cat,
        fill = n_amphi_cat),
      shape = 21,
      color = 'black',
      stroke = 0.25,
      alpha = 0.5) +
  scale_size_manual(
    name = "Nombre d'amfiteatres",
    values = c(2.5, 5, 7.5, 10),
    drop = FALSE) +
  scale_fill_manual(
    name = "Nombre d'amfiteatres",
    values = viridis::viridis(n = 4, option = 'D', direction = -1),
    drop = FALSE) +
  theme_minimal() +
  labs(
    title = 'Distribució d\'amfiteatres romans',
    subtitle = 'Per nombre i ubicació actual',
    x = 'Província Romana',
    y = 'País Modern') +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
      axis.text.y = element_text(size = 10),
      legend.position = 'bottom',
      legend.direction = 'horizontal',
      legend.title = element_text(size = 10),
      legend.text = element_text(size = 8),
      plot.margin = margin(10, 10, 10, 10))
)
```
