
# --- P-value formatting function ---
NULL
#' @title Adjust p-values for multiple comparisons
#' @description This 'pipe-friendly' function adds columns with adjusted p-values
#' and their textual representation to a 'data.frame'.
#' @param df The 'data.frame' containing the p-value column.
#' @param p_col The name of the column containing the raw (unadjusted) p-values.
#' Defaults to `"p"`, which is the common column name generated by `rstatix`.
#' @param p_digits Defaults to 3. Rounds the final p-value to this number of decimals.
#' @param method Method for adjusting p-values. Includes 'holm', 'hochberg', 'hommel',
#' 'bonferroni', 'BH', 'BY', 'fdr', 'none'. Defaults to 'holm'.
#' @param trend Logical. If `TRUE`, uses a "trend" approach to
#' textually represent adjusted p-values (e.g., 'P < 0.1'). Defaults to `FALSE`.
#' @return A 'data.frame' with the new columns added: `raw_pval_text`,
#' `raw_pval_signif`, `adj_pval`, `adj_pval_text`, and `adj_pval_signif`.
#' @importFrom dplyr rename all_of mutate case_when
#' @importFrom rstatix adjust_pvalue
#' @seealso \code{\link[rstatix]{adjust_pvalue}}
#' @rdname format_pvalue
#' @examples
#' \dontrun{
#' library(rstatix)
#' # Create an example data.frame
#' df_test <- data.frame(
#'   group = c("A", "B", "C"),
#'   p = c(0.001, 0.02, 0.1)
#' )
#'
#' # Adjust p-values using the default 'p' column
#' format_pvalue(df_test, method = "bonferroni")
#'
#' # Adjust p-values specifying a different column name
#' df_test2 <- data.frame(
#'   group = c("A", "B", "C"),
#'   p.value = c(0.001, 0.02, 0.1)
#' )
#' format_pvalue(df_test2, p_col = "p.value", method = "holm")
#' }
#' @export
format_pvalue <- function(
  df,
  p_col = 'p',
  p_digits = 3,
  method = c('holm', 'hochberg', 'hommel', 'bonferroni', 'BH', 'BY',  'fdr', 'none'),
  trend = FALSE)
{
  ## NC == did not converge
  ## NP == did not perform test
  ## NS == not significant

  method <- match.arg(method)

  if (!p_col %in% names(df)) {
    
    stop(paste0('P-value column not found in the data frame.'))
  }

  df <- df %>%
    dplyr::rename(raw_pval = dplyr::all_of(p_col))

  df <- df %>%
    dplyr::mutate(
      raw_pval_text = factor(dplyr::case_when(
        is.nan(raw_pval) ~ 'NC',
        is.na(raw_pval) ~ 'NP',
        raw_pval <= 0.0001 ~ 'P < 0.0001',
        raw_pval <= 0.001 ~ 'P < 0.001',
        raw_pval <= 0.05 ~ paste0('P = ', round(raw_pval, 3)),
        TRUE ~ 'NS'
      )),
      raw_pval_signif = factor(dplyr::case_when(
        is.nan(raw_pval) ~ 'NC',
        is.na(raw_pval) ~ 'NP',
        raw_pval <= 0.0001 ~ '***',
        raw_pval <= 0.001 ~ '**',
        raw_pval <= 0.01 ~ '*',
        raw_pval <= 0.05 ~ '.',
        TRUE ~ 'NS'
      )),
      adj_pval = rstatix::adjust_pvalue(raw_pval, method = method)
    )

  if (trend) {
    df <- df %>%
      dplyr::mutate(
        adj_pval_text = factor(dplyr::case_when(
          is.nan(adj_pval) ~ 'NC',
          is.na(adj_pval) ~ 'NP',
          adj_pval <= 0.01 ~ 'P < 0.01',
          adj_pval <= 0.05 ~ 'P < 0.05',
          adj_pval <= 0.1 ~ paste0('P = ', round(adj_pval, 3)),
          TRUE ~ 'NS'
        )),
        adj_pval_signif = factor(dplyr::case_when(
          is.nan(adj_pval) ~ 'NC',
          is.na(adj_pval) ~ 'NP',
          adj_pval <= 0.01 ~ '***',
          adj_pval <= 0.05 ~ '**',
          adj_pval <= 0.1 ~ '*',
          TRUE ~ 'NS'
        ))
      )
  } else {
    df <- df %>%
      dplyr::mutate(
        adj_pval_text = factor(dplyr::case_when(
          is.nan(adj_pval) ~ 'NC',
          is.na(adj_pval) ~ 'NP',
          adj_pval <= 0.0001 ~ 'P < 0.0001',
          adj_pval <= 0.001 ~ 'P < 0.001',
          adj_pval <= 0.05 ~ paste0('P = ', round(adj_pval, 3)),
          TRUE ~ 'NS'
        )),
        adj_pval_signif = factor(dplyr::case_when(
          is.nan(adj_pval) ~ 'NC',
          is.na(adj_pval) ~ 'NP',
          adj_pval <= 0.0001 ~ '***',
          adj_pval <= 0.001 ~ '**',
          adj_pval <= 0.01 ~ '*',
          adj_pval <= 0.05 ~ '.',
          TRUE ~ 'NS'
        ))
      )
  }

  return(df)
}


# --- ggplot2 theme selection function ---

#' @title Quick configuration and customization of ggplot2 themes
#'
#' @description
#' Applies a custom theme configuration to a ggplot2 object, allowing
#' a choice between several base themes (`theme_linedraw`, `theme_bw`, etc.) and
#' applying uniform formatting adjustments (typography, titles, X-axis text)
#' to maintain visual consistency.
#'
#' @details
#' The function is designed to reduce redundancy in customizing
#' ggplot2 plots. All common customization options
#' (such as font, size, and title alignment) are applied
#' consistently regardless of the chosen base theme. The 'bw' theme
#' has specific adjustments for grid cleaning and slightly different text sizes.
#' It returns an object of class 'theme' that should be added to the plot with the `+` sign.
#'
#' @param font_family Main font family to use for all plot text.
#'   Default: \code{'Arial'}
#' @param aspect_ratio Aspect ratio (width/height) of the plot panel.
#'   Use a numeric value (e.g., 1 for a square). Default: \code{NULL}.
#' @param legend_position Position of the legend. Can be \code{'bottom'}, \code{'right'}, or \code{'none'}.
#'   Default: \code{'bottom'}.
#' @param base_theme Base ggplot2 theme to use. Options: \code{'linedraw'}, \code{'gray'},
#'   \code{'classic'}, \code{'bw'}, \code{'minimal'}, \code{'light'}. Default: \code{'linedraw'}.
#' @return A \code{theme} object, which can be added to a ggplot with \code{+}.
#'
#' @rdname theme_ggplot
#'
#' @examples
#' \dontrun{
#' library(ggplot2)
#' # Create a base plot
#' p <- ggplot(mtcars, aes(mpg, hp, color = factor(cyl))) +
#'   geom_point() +
#'   labs(title = 'Example Plot')
#'
#' # Apply the 'bw' theme with legend on the right
#' p + theme_ggplot(base_theme = 'bw', legend_position = 'right')
#'
#' # Apply the 'minimal' theme with a square aspect ratio
#' p + theme_ggplot(base_theme = 'minimal', aspect_ratio = 1)
#' }
#' @export
theme_ggplot <- function(
  font_family = 'Arial',
  aspect_ratio = NULL,
  legend_position = c('bottom', 'right', 'none'),
  base_theme = c('linedraw', 'gray', 'classic', 'bw', 'minimal', 'light'))
{
### Validation and selection of default arguments
  legend_position <- match.arg(legend_position)
  base_theme <- match.arg(base_theme)

### Selection of the base theme (using switch for efficiency and clarity)
  selected_base_theme <- switch(
    base_theme,
      'classic' = theme_classic(),
      'bw' = theme_bw(),
      'minimal' = theme_minimal(),
      'light' = theme_light(),
      'gray' = theme_gray(),
      'linedraw' = theme_linedraw(),
    theme_bw())

### Definition of common elements for all themes
  common_elements <- list(
    legend.position = legend_position,
    text = element_text(family = font_family),
    plot.title = element_text(size = 12, hjust = 0.5, face = 'bold'),
    axis.text.x = element_text(size = 9, angle = 90, hjust = 0.95, vjust = 0.9),
    axis.title = element_text(size = 12, face = 'bold'),
    aspect.ratio = aspect_ratio)

### Specific adjustments (only for 'theme_bw')
  if (base_theme == 'bw') {
  
    specific_elements <- list(
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      strip.background = element_rect(fill = 'white'),
      strip.text = element_text(colour = 'black', size = 14, face = 'bold'),
      axis.text.x = element_text(size = 12, angle = 45, vjust = 1, hjust = 1, face = 'bold'),
      axis.text.y = element_text(size = 12, angle = 0, face = 'bold'),
      legend.title = element_text(size = 9),
      legend.text = element_text(size = 10),
      plot.title = element_text(size = 13, hjust = 0.5),
      axis.title = element_text(size = 12))
        
    final_theme <- selected_base_theme + do.call(theme, specific_elements)

    } else {

    ### Application of common elements to most themes
      final_theme <- selected_base_theme + do.call(theme, common_elements)
    
    }

### Return the theme object
  return(final_theme)

}